# Generated by Django 4.1.2 on 2022-12-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bears', '0002_alter_bears_sighting_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bears',
            name='sighting_photo',
        ),
    ]
